---
abstract: 'Math is HARD (faster)'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alt-Acme-Math-XS-ModuleBuild
provides:
  Acme::Math::XS:
    file: lib/Acme/Math/XS.pm
    version: v0.0.1
  Acme::Math::XS::Inline:
    file: lib/Acme/Math/XS/Inline.pm
  Alt::Acme::Math::XS::ModuleBuild:
    file: lib/Alt/Acme/Math/XS/ModuleBuild.pm
    version: v0.0.1
requires:
  Test::More: '0'
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.1
